apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm.yaml
patches:
- target:
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    kind: HelmRelease
    name: cert-manager
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/values/serviceAccount
      value:
          annotations:
            iam.gke.io/gcp-service-account: dns01-solver@phx-01h8eq9sbx7d19zsvqk7t9zymr.iam.gserviceaccount.com

