steps:
  - id: "generate-image-name"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/app/app:$BRANCH_NAME-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    dir: app
    args: 
      - "-c"
      - |
        image=$(cat /workspace/imagename)
        echo $image
        docker build -t $image .

  - id: "scan"
    name: ghcr.io/aquasecurity/trivy
    dir: app
    entrypoint: "/bin/sh"
    args: 
      - "-c"
      - |
        image=$(cat /workspace/imagename)
        echo $image
        trivy image $image

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    dir: app
    args: 
      - "-c"
      - |
        image=$(cat /workspace/imagename)
        docker push $image
