---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  interval: 2h0m0s
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
  install:
    crds: Create
  interval: 2h0m0s
  releaseName: crossplane-stable
  targetNamespace: crossplane-system
  upgrade:
    crds: CreateReplace
