apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: gcr-credentials
      containers:
        - name: server
          image: northamerica-northeast1-docker.pkg.dev/phx-01h57q8t23amkhpscfjenrp9y2/app/app:main-ccb4722-1696431676 # {"$imagepolicy": "flux-system:server"}
          ports:
            - containerPort: 8000
