apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: server
  labels:
    app: postgres-cluster
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 2
  primaryUpdateStrategy: unsupervised

  # PostGres Best Practices for the Logging
  #  - https://www.enterprisedb.com/blog/how-get-best-out-postgresql-logs
  #  - https://medium.com/google-cloud/correlate-statement-logs-in-cloudsql-for-postgres-with-connection-sessions-5bae4ade38f5
  postgresql:
    pg_hba:
      - host all all all md5

  bootstrap:
    initdb:
      database: polls
      owner: app

  storage:
    storageClass: local-path
    size: 300Mi
