apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - port: 8000
      targetPort: 8000
