apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    testing.upbound.io/name: registry-reader
  name: registry-reader
spec:
  deletionPolicy: Delete
  forProvider:
    displayName: registry-reader
    description: To read images from the artifact registry
  providerConfigRef:
    name: provider-gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  labels:
    testing.upbound.io/name: registry-reader-role
  name: registry-reader-role
spec:
  deletionPolicy: Delete
  forProvider:
    project: phx-01h57q8t23amkhpscfjenrp9y2
    member: "serviceAccount:registry-reader@phx-01h57q8t23amkhpscfjenrp9y2.iam.gserviceaccount.com"
    role: roles/artifactregistry.reader
  providerConfigRef:
    name: provider-gcp
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  labels:
    testing.upbound.io/example-name: registry-workload-user
  name: registry-workload-user
spec:
  deletionPolicy: Delete
  forProvider:
    member: serviceAccount:phx-01h57q8t23amkhpscfjenrp9y2.svc.id.goog[flux-system/gcr-credentials-sync]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: registry-reader
  providerConfigRef:
    name: provider-gcp
