apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: server-migrations
          image: northamerica-northeast1-docker.pkg.dev/phx-01h57q8t23amkhpscfjenrp9y2/app/app:main-ccb4722-1696431676 # {"$imagepolicy": "flux-system:server"}
          command: ["/bin/sh"]
          args:
            - "-c"
            - python manage.py migrate
          envFrom:
            - configMapRef:
                name: polls-config
          env:
            - name: DATABASE_HOST
              value: postgres-cluster-rw
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: password
