name: Update YAML
on:
  issue_comment:
    types: [created]
jobs:
  update-yaml:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
